jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pytest
          name: Test
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build