jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: flake8 stub_analyzer testing
          name: Lint
      - run:
          command: mypy stub_analyzer testing
          name: Typecheck
      - run:
          command: pytest
          name: Test
orbs:
  python: circleci/python@0.2.1
version: 2.1
workflows:
  main:
    jobs:
      - build