jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python -m flake8 stubalyzer testing
          name: Lint
      - run:
          command: python -m mypy stubalyzer testing --exclude 'testing/(stubs-generated|test-stubs/test_compile_error_invalid_syntax|test-stubs/test_include_private/attr|stubs-handwritten)'
          name: Typecheck
      - run:
          command: python -m pytest
          name: Test
orbs:
  python: circleci/python@1.3.5
version: 2.1
workflows:
  main:
    jobs:
      - build