jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m flake8 stub_analyzer testing
          name: Lint
      - run:
          command: python -m mypy stub_analyzer testing
          name: Typecheck
      - run:
          command: python -m pytest
          name: Test
orbs:
  python: circleci/python@0.2.1
version: 2.1
workflows:
  main:
    jobs:
      - build